repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        args: ["--line-length", "100"]
  # use a single ai instruction file (.cursorrules) that is kept in sync for all tools
  - repo: local
    hooks:
      - id: sync-ai-instructions
        name: sync ai instructions
        entry: bash -c 'cp .cursorrules .github/copilot-instructions.md'
        language: system
        files: ^\.cursorrules$
