# SPDX-License-Identifier: GPL-2.0-only
name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', 'pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel numpy
          pip install -r requirements-dev.txt

      # - name: Ruff (lint)
      #   run: ruff check .

      # - name: Black (format check)
      #   run: |
      #     black --check custom_components/fansync fansync examples tests

      # - name: Mypy (type check)
      #   run: mypy .

      - name: Pytest (with coverage)
        run: pytest -q --cov=custom_components/fansync --cov-report=term-missing --cov-fail-under=60
